services:

  client:
    build:
      context: ./client
    container_name: coding-app-client
    command: npm run dev
    networks:
      - local
    ports:
      - "5174:5174"

  server:
    build:
      context: ./server
    container_name: coding-app-server
    command: flask run --host=0.0.0.0 --port=8080
    networks:
      - local
    volumes:
      - ./server/src:/app
    ports:
      - "8080:8080"

networks:
  local:
